# Generated by Django 5.2.8 on 2025-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('pname', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('stock_qty', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('supplier', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
