# Generated by Django 5.2.8 on 2025-11-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProdInvApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prod',
            new_name='Product',
        ),
    ]
